apiVersion: apps/v1
kind: Deployment
metadata:
  name: calcapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calcapi
  template:
    metadata:
      labels:
        app: calcapi
        app.kubernetes.io/name: calcapi
        app.kubernetes.io/instance: calcapi
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: calcapi-suite
        app.kubernetes.io/managed-by: Helm
    spec:
      terminationGracePeriodSeconds: 600
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
      containers:
        - name: calcapi
          image: m4gapower/calcapi:1.13.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "500Mi"
              cpu: "1"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
